apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: myapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: 129762072419.dkr.ecr.us-east-1.amazonaws.com/app/app3:latest
        ports:
        - containerPort: 8080
        resources:
          # <--- ADD THIS
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
